import { withAuth } from '@/lib/api/auth';
import { validateRequest, type Schema } from '@/lib/api/validator';
import { DbService } from '@/lib/api/services/db';
import { RateLimiterService } from '@/lib/api/services/rate-limiter';
import { ApiError } from '@/lib/api/errors';
import { analyzeSeoDeterministically } from '@/lib/seo/analyzer';
import { scoreSeoDeterministically } from '@/lib/seo/scoring';
import { SeoAiAssistant } from '@/lib/seo/ai-assistant';
import type { User, SupabaseClient } from '@supabase/supabase-js';

export const runtime = 'nodejs';

// Validation schema for SEO analysis request
const analyzeSeoSchema: Schema = {
  focus_keyword: {
    required: true,
    type: 'string',
    minLength: 1,
    maxLength: 200,
  },
  meta_title: {
    required: false,
    type: 'string',
    maxLength: 300,
  },
  meta_description: {
    required: false,
    type: 'string',
    maxLength: 1000,
  },
  content: {
    required: false,
    type: 'string',
    maxLength: 50000,
  },
};

export const POST = withAuth(async (req: Request, user: User, supabase: SupabaseClient) => {
  let body: unknown;
  try {
    body = await req.json();
  } catch {
    throw new ApiError('Invalid JSON request body', 'VALIDATION_ERROR', 400);
  }

  // Reject unexpected fields (like user_id, id, score)
  validateRequest(body, analyzeSeoSchema, {
    allowUnknown: false,
    requireAtLeastOne: false,
  });

  const payload = body as {
    focus_keyword: string;
    meta_title?: string;
    meta_description?: string;
    content?: string;
  };

  // 1. Run Deterministic Text Analyzer
  const deterministicAnalysis = analyzeSeoDeterministically({
    focusKeyword: payload.focus_keyword,
    metaTitle: payload.meta_title,
    metaDescription: payload.meta_description,
    content: payload.content,
  });

  // 2. Compute Deterministic Numerical Score (0-100) & Rule Recommendations
  // MUST NOT be modified or generated by AI
  const scoringResult = scoreSeoDeterministically(deterministicAnalysis);

  const dbService = new DbService(supabase, user.id);

  // 3. AI Semantic Assistant (Enrichment only with atomic DB rate limiting)
  let usageId: string | undefined;
  let aiResult;

  try {
    usageId = await RateLimiterService.checkAndReserveQuota(
      dbService,
      'seo-analyze',
      'google/gemini-3.7-flash'
    );

    const aiAssistant = new SeoAiAssistant();
    aiResult = await aiAssistant.analyzeSemantics({
      focusKeyword: payload.focus_keyword,
      metaTitle: payload.meta_title,
      metaDescription: payload.meta_description,
      content: payload.content,
    });
    await dbService.markAiUsageCompleted({ usageId });
  } catch (aiErr: any) {
    if (usageId) {
      await dbService.markAiUsageFailed({
        usageId,
        errorMessage: aiErr?.message || 'SEO AI analysis failed',
      });
    }
    if (aiErr?.code === 'RATE_LIMIT_EXCEEDED' || aiErr?.statusCode === 429) {
      throw aiErr;
    }
    console.warn('SEO API: AI Semantic Assistant unavailable, falling back gracefully:', aiErr);
    aiResult = {
      keywords: {
        primary: [{ word: payload.focus_keyword, searchVolume: 'Est. 10K', difficulty: 'Medium' as const }],
        secondary: [],
        longTail: [],
        related: [],
      },
      semanticRecommendations: [],
    };
  }


  // Combine deterministic recommendations + AI semantic recommendations
  const combinedRecommendations = [
    ...scoringResult.recommendations,
    ...(aiResult.semanticRecommendations.map((sr) => ({
      type: sr.type,
      category: 'content' as const,
      message: sr.text,
      priority: 'medium' as const,
    }))),
  ];

  const analysisPayload = {
    deterministic: deterministicAnalysis,
    breakdown: scoringResult.breakdown,
    recommendations: combinedRecommendations,
    keywords: aiResult.keywords,
  };

  // 4. Supabase Persistence via DbService (RLS protected)
  let savedId = undefined;
  let createdAt = new Date().toISOString();

  try {
    const dbService = new DbService(supabase, user.id);
    const savedRecord = await dbService.createSeoAnalysis({
      focus_keyword: payload.focus_keyword,
      meta_title: payload.meta_title,
      meta_description: payload.meta_description,
      content: payload.content,
      score: scoringResult.overallScore,
      analysis_result: analysisPayload,
    });
    savedId = savedRecord.id;
    createdAt = savedRecord.created_at;
  } catch (dbErr: any) {
    console.warn("Notice: Supabase persistence skipped (table migration pending on remote DB):", dbErr?.message || dbErr);
  }

  return Response.json({
    success: true,
    data: {
      id: savedId,
      score: scoringResult.overallScore,
      breakdown: scoringResult.breakdown,
      analysis: deterministicAnalysis,
      recommendations: combinedRecommendations,
      keywords: aiResult.keywords,
      created_at: createdAt,
    },
  });
});
